name: lvoapp
description: "LVO - Social media application for sharing photos and videos"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.0
  dio: ^5.7.0
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  uuid: ^4.5.1
  path: ^1.9.1
  path_provider: ^2.1.5
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  google_sign_in: ^6.2.1
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - lib/core/config/.env
    - assets/images/
    - lvo.png

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lvo.png"
  adaptive_icon_background: "#000815"
  adaptive_icon_foreground: "lvo.png"
